### ISSUE TITLE
Unattended installation not unattended

### ISSUE THREAD

**Issue by Untitled-Document-1** [RealRemanex/Zorin-preseed#2]
Thank you for creating this repo! I think it will be very helpful for an [IT Reuse project](https://communityfurniturestore.co.uk/wordpress/it-reuse/) I am involved in here in the U.K.

I am having a problem in that the bootable USB stick I have created is still functioning like a vanilla "attended" install. For example, I still have to double-click the `Install Zorin OS` icon on the live CD desktop to get it to start installing, and I still have to answer questions like what the locale should be, and what keyboard type to use.

These are the steps I am following to prepare my bootable USB stick:

```
sudo su -
apt install syslinux-utils # needed for isohybrid
cd /
mkdir zorin-files
cd zorin-files
git clone https://github.com/wlw-benjaminbraendli/Zorin-preseed
# Download the Zorin OS 15.3 Lite ISO to the working directory
mkdir mnt-dir
mount -o loop Zorin-OS-15.3-Lite-64-bit.iso mnt-dir/
rsync -a mnt-dir/ ISO/
umount mnt-dir && rm -rf mnt-dir # cleanup; I'm finished with the vanilla ISO
rsync -a Zorin-preseed/files ISO/files
cp Zorin-preseed/*.preseed ISO
cp Zorin-preseed/*.sh ISO
cp Zorin-preseed/locale ISO
cp Zorin-preseed/menuentries.cfg ISO/isolinux
cp Zorin-preseed/grub.cfg ISO/boot/grub
mkisofs -D -r -V "UNATTENDED_ZORIN" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o unattended-Zorin.iso ISO
isohybrid unattended-Zorin.iso # make ISO bootable
blkid # identify USB disk (/dev/sdX)
dd if=/zorin-files/unattended-Zorin.iso of=/dev/sdc bs=4M; sync
```

I wonder whether I am copying the repo files (`*.preseed`, `*.sh`)  into the correct path within the `ISO` directory? If everything looks correct, can you think of any other reason why the installation wouldn't be (mostly) unattended? (I understand from your `README.md` that the installation will not be fully unattended)

During my testing, I chose the second option `Install Zorin OS erase` from the menu. Looking at the completed installation, the language settings from the `locale` file _have_ been honoured, however, the user account name from the preseed file has not, with the account name I entered during the installation wizard used instead.

Finally, I [forked your repo](https://github.com/Untitled-Document-1/Zorin-preseed), so that I can incorporate my own customisations to things like the locale and language. I have also edited the `README.md`, so feel free to pull my edits across if you think they are useful.

Thank you!

**Comment by wlw-benjaminbraendli** [comment]
Hello,
I'm pleased to hear, that the repo is useful.
Which version of Zorin do you use?
All files should be in the root of the ISO, except the README says something different
There shouldn't be the posibility in the wizard to enter a username, if the preseeding works.
I think the problem is, that you have inserted the password in clear text.
The option in my file uses an encrypted password. You can lookup the hash in an installed system in the /etc/shadow file.
Or you can change the `d-i passwd/user-password password insecure` option to enter the password in clear text.
We use the password `admin`, so feel free to use this.
The only part in the installation, which isn't unattended, is the question of the partition scheme. The other questions shouldn't be asked.
Since we change the localisation in the final installation, i have copied the localisation options from the examples in the net.

If you have further questions or if i have overseen a question, feel free to ask.

Have a nice evening.

**Comment by Untitled-Document-1** [comment]
Hello,

Thanks for the reply. I am using `Zorin OS 15.3 Lite 64-bit`. Is this a version you have tested with, by any chance? I also tested it using your repo, without my customisations, and I faced the same problem of it asking all the questions, as per a regular installation.

Thank you for noticing that my password references were unencrypted. That was an oversight on my part. I have now corrected this. I don't think this will help the unattended problem, so if the problem remains, I will try using Zorin Core instead.

I will report back soon. I really appreciate your support!

**Comment by wlw-benjaminbraendli** [comment]
Hello,

We work with the Zorin OS 115.3 Core.
Do you have the two bootmenue-files `grub.cfg` and `menuentris.cfg` in the corresponding directory. These two files give the installer the path to the preseeding files. If you have them in the root directory, the installer  won't find them.

The file `menuetries.cfg` has to be in the directory `/isolinux` and the file `grub.cfg` has to be in the directory `/boot/grub`.

Feel free to ask, if there are questions left or new questions arrive

I wish you the best for you an your project.

**Comment by Untitled-Document-1** [comment]
Hello,

Yes, I have the two files in the corresponding directories. I tried using `Zorin OS 15.3 Core 64-bit` but unfortunately the problem is the same; nothing happens after reaching the live desktop:

![VirtualBox_Zorin Lite_27_03_2021_16_33_00](https://user-images.githubusercontent.com/19150360/112727443-67e64d00-8f1a-11eb-87c6-86d372262bff.png)

The screenshot is from Oracle VirtualBox but the problem also exists on a laptop I'm testing with.

I've tried a few things, like fixing the odd typo and changing the whitespace from tabs to spaces in `menuentries.cfg` & `grub.cfg`, but that doesn't seem to be the problem; the same thing occurs if I use the files from your repo, rather than my fork. This makes me think that I'm doing something wrong in the way I'm preparing the ISO image (the steps in my first post).

I will rack my brains for ideas. I have no prior experience of automating Linux installs, but maybe I'll come up with something.

Cheers! 😊

**Comment by wlw-benjaminbraendli** [comment]
Hello,

I think I have found the problem. We have additional changes in charge and i have removed an entry in the bootmenue, which start the installer. We start the installer with a script in the livesystem.

You have now two posibilities.
The first is to add `automatic-ubiquity` in the long line of all six bootentries in both of the bootmenues.
The second is tho enter the command `sudo ubiquity --automatic` in the shell of the live-system.

The first will start the installer direct at boottime. The second  will start it from the live-system.
The second option is only usefull, if you have things to do in the livesystem befor the installation.

I hope this will help you. 
If not, fell free to ask again.

HAve a nice evening.

**Comment by Untitled-Document-1** [comment]
Thank you very much; the `automatic-ubiquity` option has solved the problem! 😁🎉
Have a good evening too.
